### ISSUE TITLE
why when i try to compile this project i get this error?

### ISSUE THREAD

**Issue by Skyue1** [matcool/ReplayBot#33]
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Users/user/Desktop/Project/ReplayBot-1.4.2/build/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log](https://github.com/matcool/ReplayBot/files/9080936/CMakeOutput.log)

**Comment by matcool** [comment]
i dont get this error :+1:
